volumes:
  postgres-data:
  composer-data:

services:
  memcached:
    image: memcached:1.6.33-alpine
    expose:
      - 11211

  postgres:
    image: postgres:17.2-alpine
    environment:
      POSTGRES_DB: project
      POSTGRES_USER: project
      POSTGRES_PASSWORD: project
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./docker/var/db-dumps/:/docker-entrypoint-initdb.d/
    expose:
      - 5432
    ports:
      - 5432:5432

  php-fpm:
    build:
      context: docker/php-fpm
      args:
        DOCKER_HOST_UID: $DOCKER_HOST_UID
        MEMCACHED_VERSION: $MEMCACHED_VERSION
        COMPOSER_VERSION: $COMPOSER_VERSION
    volumes:
      - ./project:/var/www/project:cached
      - composer-data:/home/www-data/.composer/
      - ./docker/php-fpm/php-fpm/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
      - ./docker/php-fpm/xdebug/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini:ro
    expose:
      - 9000
    links:
      - memcached
      - postgres

  nginx:
    image: nginx:1.27.3-alpine
    volumes:
      - ./project:/var/www/project:cached
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/site.conf
    ports:
     - 80:80
     - 443:443
    links:
      - php-fpm
