services:
  mysql:
    image: mysql:${MYSQL_VERSION}
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      MYSQL_DATABASE: db_name
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    volumes:
      - ./docker/mysql:/etc/mysql/conf.d
    ports:
      - 3306:3306

  postgres:
    image: postgres:${POSTGRESQL_VERSION}
    environment:
      POSTGRES_DB: db_name
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - 5432:5432

  memcached:
    image: memcached:1.6.33-alpine
    expose:
      - 11211

  php-fpm:
    build:
      context: docker/php-fpm
      args:
        DOCKER_HOST_UID: $DOCKER_HOST_UID
        MEMCACHED_VERSION: $MEMCACHED_VERSION
    volumes:
      - ./project:/var/www/project
      - ./docker/php-fpm/php-fpm/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
      - ./docker/php-fpm/xdebug/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini:ro
    expose:
      - 9000
    links:
      - memcached
      - postgres
      - mysql

  nginx:
    image: nginx:1.27.3-alpine
    volumes:
      - ./project:/var/www/project:cached
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/site.conf
    ports:
      - 80:80
      - 443:443
    links:
      - php-fpm
